### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_CustomTweaks#1]
Message: ...dOns\ElvUI_CustomTweaks\categories\chat\MaxLines.lua:48: attempt to index global 'self' (a nil value)
Time: 10/10/16 23:30:17
Count: 1
Stack: ...dOns\ElvUI_CustomTweaks\categories\chat\MaxLines.lua:48: in function <...dOns\ElvUI_CustomTweaks\categories\chat\MaxLines.lua:40>

Interface\AddOns\ElvUI\core\core.lua:837: in function `InitializeModules'
Interface\AddOns\ElvUI\core\core.lua:939: in function`Initialize'
Interface\AddOns\ElvUI\init.lua:125: in function <Interface\AddOns\ElvUI\init.lua:124>

Locals: (_temporary) = nil
(_temporary) = <table> {
 1 = "ChatFrame1"
 2 = "ChatFrame2"
 3 = "ChatFrame3"
 4 = "ChatFrame4"
 5 = "ChatFrame5"
 6 = "ChatFrame6"
 7 = "ChatFrame7"
 8 = "ChatFrame8"
 9 = "ChatFrame9"
 10 = "ChatFrame10"
}
(_temporary) = 10
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = <function> defined =[C](?):-1
(_temporary) = ChatFrame10 {
 0 = <userdata>
 flashTimer = 0
 isInitialized = 1
 tellTimer = 2756.462
 button = CopyChatButton10 {
 }
 resizeButton = ChatFrame10ResizeButton {
 }
 buttonFrame = ChatFrame10ButtonFrame {
 }
 oldAlpha = 0.15686275437474
 channelList = <table> {
 }
 clickAnywhereButton = ChatFrame10ClickAnywhereButton {
 }
 editBox = ChatFrame10EditBox {
 }
 scriptsSet = true
 isLocked = 1
 name = "Chat 10"
 SetScript = <function> defined =[C](?):-1
 styled = true
 zoneChannelList = <table> {
 }
 buttonSide = "left"
 messageTypeList = <table> {
 }
}
(_temporary) = 125
(_temporary) = "attempt to index global 'self' (a nil value)"
pairs = <function> defined =[C](?):-1
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C](?):-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 KBASE_NUM_FAKE_CATEGORIES = 1
 SetTrainerServiceTypeFilter = <function> defined =[C](?):-1
 MerchantItem6AltCurrencyFrameHonorTexture = MerchantItem6AltCurrencyFrameHonorTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture {
 }
 InterfaceOptionsDisplayPanelShowAggroPercentageText = InterfaceOptionsDisplayPanelShowAggroPercentageText {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 IsReferAFriendLinked = <function> defined =[C](?):-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @Interface\FrameXML\MoneyFrame.lua:184
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Battle.net may be unavailable."
 WatchFrameItem_OnEvent = <function> defined @Interface\FrameXML\WatchFrame.lua:1206
 InterfaceOptionsCombatTextPanelFCTDropDown_OnClick = <function> defined @Interface\FrameXML\InterfaceOptionsPanels.lua:1349
 LFGTeleport = <function> defined =[C](?):-1
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ChannelMemberButton10Name = ChannelMemberButton10Name {
 }
 PetStableMoneyFrameGoldButtonText = PetStableMoneyFrameGoldButtonText {
 }
 VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 FlightMapTooltipTextRight3 = FlightMapTooltipTextRight3 {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 PetPaperDollFrameTab

**Comment by Bunny67** [comment]
Check

**Comment by Bunny67** [comment]
Close?
