### ISSUE TITLE
Ошибки при в ходе в игру

### ISSUE THREAD

**Issue by Suonu** [ElvUI-WotLK/ElvUI_CustomTweaks#10]
Каждый раз при заходе в игру или /reload выскакивают ошибки, пока не заметил на что они влияют
https://imgur.com/a/kjmY5Bx
https://imgur.com/a/5HBQYQR

**Comment by Merfinx** [comment]
Не работает Unitframe Tweaks -> CastbarCustom Backdrop. 
При этом выскакивает ошибки при релоаде

https://imgur.com/a/Mvtum5f

**Comment by Bunny67** [comment]
1. Твик удален из плагина, так как больше не совместим с ElvUI.
2. Удален из плагина, так как опция появилась в самом ElvUI.
