### ISSUE TITLE
Ошибка AuraIconText

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_CustomTweaks#11]
При включении данной опции в Твиках рамок юнитов, появляется данная ошибка, которая не проходит даже после релога:

1x ..._CustomTweaks\categories\unitframes\AuraIconText.lua:201: hooksecurefunc(): UpdateAuraIconSettings is not a function:
..._CustomTweaks\categories\unitframes\AuraIconText.lua:201: in main chunk:

Locals:
E = <table> {
 GetTimeInfo = <function> @ ElvUI\Core\Math.lua:303:
 mylevel = 80
 Bags = <table> {}
 resolution = "2560x1440"
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\Core\Math.lua:342:
 ExitVehicleShowFrames = <function> @ ElvUI\Core\API.lua:302:
 HelloKittyToggle = <function> @ ElvUI\Core\AprilFools.lua:362:
 CopyTable = <function> @ ElvUI\Core\Core.lua:486:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\Core\Movers.lua:482:
 ScheduleTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RemoveEmptySubTables = <function> @ ElvUI\Core\Core.lua:502:
 SetupTheme = <function> @ ElvUI\Core\Install.lua:149:
 media = <table> {}
 UnlocalizedClassName = <function> @ ElvUI\Core\API.lua:27:
 EnableBlizzardAddOns = <function> @ ElvUI\Core\Commands.lua:198:
 UIScale = <function> @ ElvUI\Core\PixelPerfect.lua:27:
 db = <table> {}
 FramesOverlap = <function> @ ElvUI\Core\Math.lua:107:
 SetEnabledState = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 PluginInstaller = <table> {}
 PixelBestSize = <function> @ ElvUI\Core\PixelPerfect.lua:68:
 UnregisterEventForObject = <function> @ ElvUI\Core\Core.lua:986:
 Distributor = <table> {}
 HiddenFrame = <unnamed> {}
 Media = <table> {}
 UnregisterAllEvents = <function> @ Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 ScanTooltipTextures = <function> @ ElvUI\Core\API.lua:36:
 UIFrameFade = <function> @ ElvUI\Core\Animation.lua:215:
 MinimapWidth = 220
 StaticPopup_IsLastDisplayedFrame = <function> @ ElvUI\Core\StaticPopups.lua:570:
 Truncate = <function> @ ElvUI\Core\Math.lua:88:
 UpdateBackdropColors = <function> @ ElvUI\Core\Core.lua:414:
 TimeThreshold = 3
 ToggleMoveMode = <function> @ ElvUI\Core\Config.lua:55:
 RemoveTableDuplicates = <function> @ ElvUI\Core\Core.lua:523:
 name = "ElvUI"
 WorldMap = <table> {}
 MinimapHeight = 220
 Disable = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:345:
 TimeColors = <table> {}
 SlideOut = <function> @ ElvUI\Core\Animation.lua:150:
 Unhook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418:
 Print = <function> @ ElvUI\Core\Core.lua:181:
 Install = <function> @ ElvUI\Core\Install.lua:668:
 UnregisterObjectForVehicleLock = <function> @ ElvUI\Core\API.lua:274:
 RegisterCooldown = <function> @ ElvUI\Core\Cooldowns.lua:175:
 EscapeString = <function> @ ElvUI\Init.lua:110:
 TimeFormats = <table> {}
 RGBToHex = <function> @ ElvUI\Core\Math.lua:93:
 InversePoints = <table> {}
 HealingClasses = <table> {}
 loadedtime = 37703.328
 Tutorials = <function> @ ElvUI\Core\Tutorials.lua:110:
 UpdateNudgeFrame = <function> @ ElvUI\Core\Config.lua:207:
 ShortPrefixStyles = <table> {}
 GetCPUImpact = <function> @ ElvUI\Core\Commands.lua:148:
 SetDefaultModuleLibraries = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:398:
 ProfileTableToPluginFormat = <function> defined @Elv
  ---

**Comment by Vitoshka** [comment]
С этой ошибкой пропала возможность изменять данные **[настройки](https://c.radikal.ru/c08/1908/9a/9ae0ea04b503.jpg)**

**Comment by Bunny67** [comment]
Твик удален из плагина, так как больше не совместим с ElvUI.

**Comment by Vitoshka** [comment]
А сделать перемещение текста таймера и текста стаков теперь нет возможности в иконках баффов дебаффов и тд.?
