### ISSUE TITLE
[Minor] Error when loging-in

### ISSUE THREAD

**Issue by Will-Scarlet** [ElvUI-WotLK/ElvUI_CustomTweaks#6]
Date: 2017-07-29 15:22:40
ID: 1
Error occured in: Global
Count: 1
Message: ...ustomTweaks\categories\nameplates\NameplatesText.lua line 4:
   attempt to index field 'nameplate' (a nil value)
Debug:
   [C]: ?
   ...ustomTweaks\categories\nameplates\NameplatesText.lua:4: in main chunk
AddOns:
  Swatter, v3.1.14 (<%codename%>)
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  DBMCore, v
  EasyLoot, v1.7.0.0
  ElvUI, v5.35
  ElvUIAddOnSkins, v1.01
  ElvUICustomTweaks, v1.30
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.wowgasm-reloaded.org>
  (ck=f7)

**Comment by Loaal** [comment]
Nameplate tweak was removed.
Make sure you are using latest version.
Also better way to update addons is to remove folder with older version and after that copy new one into AddOns folder.
