### ISSUE TITLE
[Bug] PowerBarTexture doesn't get applied to group

### ISSUE THREAD

**Issue by snwflake** [ElvUI-WotLK/ElvUI_CustomTweaks#7]
Although I set the PowerBarTexture to `Flat`, it doesn't get applied when joining a group.

![](https://snwflk.ml/2HiSz1N)

If I want the texture to change, I'd go to `ElvUI > UnitFrames > Party Frames > Power` and toggle the `Style` property from `Filled` to something else and back.
Only that way all partyframe powerbars get updated to `Flat`.

I also checked, that the right key is present in my db file, which appears to be the case:
```lua
["CustomTweaks"] = {
	["PowerBarTexture"] = {
		["powerstatusbar"] = "Flat",
	},
},
```

**Comment by snwflake** [comment]
Any news?

**Comment by Bunny67** [comment]
Check

**Comment by snwflake** [comment]
Working as expected.
/close
